### ISSUE TITLE
Testing octo.erl

### ISSUE THREAD

**Issue by Minoru** [sdepold/octo.erl#24]
In #22, @sdepold wrote:
> Guess I will have to mock the test requests :(

So I've been looking into how others test their GitHub bindings, and it looks like the best way is employing two sets of tests:
* unit tests that only check that the URLs generated by the bindings are correct;
* integration tests that actually run against live GitHub.

Unit tests are run by Travis; integration ones are run by developers themselves. Integration tests require the developer to create an account for testing purposes.

What we have at the moment can be described as "integration tests implemented using unit testing framework". Furthermore, it's nailed to one specific repo, `sdepold/octo.erl-test`.

So here's an outline of what I'm (awfully lazily) doing:
1. (done) disentangle existing tests from sdepold's test repo. Encourage developers to create their own testing accounts;
2. migrate from EUnit to Common Test (questionable, but CT is for integration tests);
3. mock http_helper so that unit tests can be written in a proper way (this one will probably be influenced by my other slowly progressing work, namely turning http_helper into an instance of gen_server that will cache the responses).

Does that make sense?

**Comment by sdepold** [comment]
Sounds very good :+1:

**Comment by sdepold** [comment]
> 2. migrate from EUnit to Common Test (questionable, but CT is for integration tests);

I have no knowledge about CT but I will trust your judgement!

**Comment by Minoru** [comment]
Should've closed this via commit message for 7868e6f7ad77e72f63e5559608a3fa92f6dbbd7c, but I've run out of my quota for force-pushes to `master` for today :)
