### ISSUE TITLE
Pagination implementation is wrong

### ISSUE THREAD

**Issue by Minoru** [sdepold/octo.erl#25]
[GitHub's API documentation](https://developer.github.com/guides/traversing-with-pagination/) specifically warns against the approach taken by octo.erl:

> Keep in mind that you should always rely on these link relations provided to you. Don't try to guess or construct your own URL. Some API calls, like listing commits on a repository, use pagination results that are based on SHA values, not numbers.

Bumped into this while writing tests (yep, #24 ain't dead :), thought it's better to file an issue.

**Comment by sdepold** [comment]
👋 any interest in taking over this project?

**Comment by Minoru** [comment]
Actually, yes. I don't have any grand plans, really, I only wanted Activity part of the API to work... But if that suits you, I'm in.

**Comment by sdepold** [comment]
Boom. You are a collaborator now. :)

**Comment by Minoru** [comment]
Yay! Thanks!

**Comment by Minoru** [comment]
Um, I think I also need access to octo.erl-test. All the branches there are even with master, I can't run integration tests for pull requests because of that :(

**Comment by sdepold** [comment]
fixed

**Comment by Minoru** [comment]
Thanks!

**Comment by Minoru** [comment]
Here's an outline of a proper implementation as I see it. (Writing it down to free up some working memory.)

Each record gets a new field, `pagination_ref`¹. When octo.erl receives a response containing `Link` header, it:
1. generates a new ref;
2. puts the value of the `Link` header into orddict or something², keyed by the ref generated earlier;
3. initialized the aforementioned `pagination_ref` field with this same ref.

We will also add a new module, `octo_pagination`, with three functions:
* `get_next/1`, which gets the next page given the previous response;
* `get_total_number/1`, which returns a number of pages in the result given any of the previous responses (extracted from the `rel="last` using a regular expression, just like they do in [the docs](https://developer.github.com/guides/traversing-with-pagination/));
* `is_last/1`, which, given a response, returns `true` or `false` depending on the presence of `rel="next"` in the response's `Link` header.

---
¹ This is subject to further meditation. A ton of partially overlapping structures is ugly; but if we create a hierarchy of them, we'll end up with accessing nested records, which are a tad ugly in Erlang.

² That's actually another reason to write this down: we need a place to store that `orddict`! Luckily, I was going to work on response caching anyway; once it's done, we'll be able to keep the orddict in the caching process.

**Comment by Minoru** [comment]
Actually, I don't see a reason not to have `get_previous/1`, `get_last/1` and `get_first/1` as well. And also `is_first/1`.

**Comment by Minoru** [comment]
The final design looks like this:

```erlang
{ok, Page1} = octo:list_pull_requests("sdepold", "octo.erl"),
{ok, Page2} = octo:list_pull_requests({next, Page1}).
```

`next`, `prev`, `first` and `last` are supported atoms.

There's a caveat, though: if you do `{ok, Page1Again} = octo:list_pull_requests({prev, Page2})`, the request will bypass the cache. This only happens with the first page of the results.

This is caused by the fact that on the first call to a function (`octo:list_pull_requests`, in this case) we're generating the URL of the endpoint ourselves, but on subsequent calls we're using URLs that GitHub gave us. For some kinds of queries, the URLs returned are nothing like the ones we generate; for example, `octo:list_commits("sdepold", "octo.erl")` will query `https://api.github.com/repos/sdepold/octo.erl/commits`, but `next` URL for this particular call is… `https://api.github.com/repositories/28632908/commits?page=2`. And when we go back from there, we'll be querying `https://api.github.com/repositories/28632908/commits?page=1`.

Since this is a corner case and it only results in minor damage (some memory lost to hold two equivalent responses, plus one unnecessary call to GitHub API) and I don't see a clear solution, I decided to give up on it. Anyone who has a good idea is welcome to suggest or, better yet, implement it.

**Comment by sdepold** [comment]
Go ahead 👍
