### ISSUE TITLE
Should octo.erl-specific options be kept as a separate argument?

### ISSUE THREAD

**Issue by Minoru** [sdepold/octo.erl#44]
#Some GitHub API endpoints accept optional arguments, e.g. `body` in ["Create pull request"](https://developer.github.com/v3/pulls/#create-a-pull-request) or all the stuff in ["List pull requests"](https://developer.github.com/v3/pulls/#list-pull-requests). We don't have a set approach for handling those.

 `octo.erl` itself has some [internal options](https://github.com/sdepold/octo.erl#options) that are always passed in a list as last argument:

```erlang
All_PRs = octo:list_pull_requests("sdepold", "octo.erl", [all_pages]).
%% Convenience overload passes empty list as options
Some_PRs = octo:list_pull_requests("sdepold", "octo.erl").
```

**The question** is: should I pass GitHub's options as a separate list (let's call this option №1), or should they be merged with octo.erl's options (options №2)?

Pros of option №1:

* **no risk of name clashes** between GitHub's and octo.erl's options.
* **octo.erl can be dumb about handing GitHub's options**: just serialize them.

Cons of option №1:

* **a lot to type**. Convenience overload that passes empty lists both as GitHub's and octo.erl's options is nice, but what if you need one but not the other? There's no named parameters in Erlang, so you'll have to write something like this:
    ```erlang
    All_PRs = octo:list_pull_requests("sdepold", "octo.erl", [], [all_pages]).
    ```
* **higher chance of breaking an API compatibility**. Not all endpoints accept options, so not all of our functions will provide a parameter to pass them. But if GitHub adds some, it will be backward-compatible for them but not for us (because `octo:f(X, Options)` will suddenly become `octo:f(X, Payload, Options)`.)

The options are symmetrical so the cons of option №1 are pros of option №2 and vice versa.

**Comment by LavirtheWhiolet** [comment]
Option #2 is a must. The other options are just attempts to save the developer's time.

A nice compromise may be to prefix the GitHub options with something like `gh.` (`[all_pages, gh.opt1, gh.opt2, erl_opt]`). Also one may follow the GCC way (and implement something like its `gcc` `-Wl` parameter): `[all_pages, "gh,opt1,opt2", erl_opt]`.

Yet another way may be something like this:

```
All_PRs = octo:list_pull_requests("sdepold", "octo.erl", [all_pages, [github, opt1, opt2], optX])
```

**Comment by Minoru** [comment]
Oh, I somehow didn't think of prefixing some of the options! I think prefixing octo.erl's makes more sense because then the user can just copy-paste their names from the docs; just as they say: "don't make me think". Thanks!

**Comment by Minoru** [comment]
It's decided, then: I'm going to follow option №2, prefixing octo.erl's internal options with `octo_`. @LavirtheWhiolet, once again thanks for discussion!
